name: Test and Coverage for Changed Files

on:
  pull_request:
    paths:
      - '**/*.py'  # Monitor Python files for changes
    branches:
      - main       # Run only for PRs targeting the main branch

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Identify changed files
        id: changed_files
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
          echo "Changed files:"
          git diff --name-only origin/${{ github.event.pull_request.base.ref }} -- '*.py'

      - name: Run tests and collect coverage
        run: |
          coverage run -m pytest
          coverage report
          coverage xml
        continue-on-error: true

      - name: Filter coverage for changed files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} -- '*.py')
          echo "Filtering coverage for the following changed files:"
          echo "$CHANGED_FILES"
          coverage report --include="$CHANGED_FILES"

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  # comment-report:
  #   needs: run-tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download Coverage Report
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: coverage-report

  #     - name: Post coverage report to PR
  #       uses: marocchino/sticky-pull-request-comment@v2
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         header: Coverage Report
  #         message: |
  #           ```
  #           $(cat coverage.xml)
  #           ```
